name: t42design
favicon: null
layout_spectrum: 0.294086228357628
typography_spectrum: 0.8481309737544507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9481815670151263
  lightness: 0.3506733530666679
  saturation: 0.9153363618534058
  rhythmicContrast: 0.904211406596005
purpose: []
