name: le petite artiste
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7977
title: innocence makes the purist art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4b4046'
    - '#fd9903'
    - '#eb0044'
    - '#0091ba'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
