name: le petite artiste
favicon: null
layout_spectrum: 0.35549
typography_spectrum: 0.7977
title: innocence makes the purist art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4b4046'
    - '#fd9903'
    - '#eb0044'
    - '#0091ba'
  brandStrength: 1
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
