name: le petite artiste
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7977
title: innocence makes the purist art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#babbbd'
    - '#582d2f'
    - '#309d38'
    - '#d44169'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
